config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :dashboards
  resources :courses
  resources :units
  resources :levels
  resources :companies
  get 'home/index'

  devise_for :users, controllers: { registrations: 'users/registrations' }


  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  
end

app/models/ability.rb
class Ability
  def initialize(user)
    user ||= User.new
    
    can :read, :all, public: true

    return unless user.role == 'admin'
    can :crud, :all
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :courses, dependent: :destroy
    has_many :users    
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :users
    has_and_belongs_to_many :companies, dependent: :destroy
    belongs_to :level
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
    self.inheritance_column = nil 

    enum type: [:Daylight, :Evening, :Night]
end

app/models/level.rb
class Level < ApplicationRecord
    has_many :courses
    has_and_belongs_to_many :units, dependent: :destroy

end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
    has_and_belongs_to_many :levels, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :courses
  belongs_to :company

  validates :role, presence: true

  # belongs_to :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    role.name == 'Admin'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  
  def index
    @courses = current_user.courses
  end

  def edit
    authorize! :edit    
  end

  # <% if can? :destroy, course %>
  #   <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
  #   course_path(course),
  #   :method => :delete,
  #   :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
  #   :class => 'btn btn-mini btn-danger' %>
  # <% end %>

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
    @unit = Unit.new
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>FinalProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      <%= render partial:"shared/navbar" %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    
      <br>
        <div>
          <% if user_signed_in? %>
          <%#= current_user.courses %>
          <%= button_to 'Log out', destroy_user_session_path, method: :delete %>      
          <% else %>
        
          <% end %>
        </div>
    





    <%= yield %>
    </div>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">English Class</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", home_index_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "courses", courses_path, class:"nav-link"%>
        </li>
         <li class="nav-item">
        <%= link_to "levels", levels_path, class:"nav-link"%>
        </li>
        </li>
         <li class="nav-item">
        <%= link_to "Companies", companies_path, class:"nav-link"%>
        </li>
          <li class="nav-item">
        <%= link_to "Dashboard", dashboards_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Admin", admin_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Students", students_path, class:"nav-link"%>
        </li>

                
        </li>
        </ul>
    </div>
  </div>

     
</nav>